name: Docker Image CI

on:
  push:
    branches: [ "darapureddy12345-patch-6" ]
  pull_request:
    branches: [ "darapureddy12345-patch-6" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Replace with the desired .NET Core version

      - name: Build and publish Docker image
        run: |
          docker build -t myapp .
          docker tag myapp:latest my-docker-username/myapp:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u my-docker-username --password-stdin
          docker push my-docker-username/myapp:latest
