name: Docker Image CI

on:
  push:
    branches: [ "darapureddy12345-patch-6" ]
  pull_request:
    branches: [ "darapureddy12345-patch-6" ]

jobs:

  build:

    runs-on: ubuntu-latest

  buildDockerImage:
    name: Building Docker image
    runs-on: ${{ inputs.runnerName }}

    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3
      - name: Install Azure CLI
        run: |
         curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Logs in with your Azure credential
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
            # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .

  deploy:
